'use strict';
const $=s=>document.querySelector(s);
const incoming=new URLSearchParams(location.hash.slice(1)).get('access');
if(incoming){sessionStorage.setItem('farmy-workbench-access',incoming);history.replaceState(null,'',location.pathname);}
const token=sessionStorage.getItem('farmy-workbench-access');
let state=null,preview=null,busy=false;
function message(text,error=false){$('#message').textContent=text;$('#message').classList.toggle('error',error);}
const errors={denied:'Wallet denied this action. Permission is missing, revoked or outside this item’s permitted readers.',unauthenticated:'Open the private access link printed by the runner.',conflict:'The source or permission changed, or another action needs retrying. Refresh before continuing.',unavailable:'A service is unavailable. No new access has been allowed. Retry when it returns.',expired:'This permission or request expired. Restart the demo for fresh development grants.',invalid_request:'This request could not be accepted.',not_found:'This item is not available in this session.'};
async function api(path,body){const response=await fetch(path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+(token||''),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store'});const result=await response.json();if(!response.ok){const error=new Error(errors[result.error]||'The request failed.');error.code=result.error;throw error;}return result;}
function node(tag,text,cls){const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;}
function button(text,action,disabled=false){const b=node('button',text);b.disabled=disabled;b.addEventListener('click',action);return b;}
function clearResult(){$('#result').hidden=true;$('#content').textContent='';$('#content').hidden=true;}
function render(){const owner=state.role==='owner';$('#role').textContent=owner?'Owner view':'Demo consumer view';$('#heading').textContent=owner?'Your Wallet, in your hands.':'See what the consumer can read.';$('#intro').textContent=owner?'Choose one document, keep a governed copy, then test its access.':'Every attempt asks the real Wallet for a current decision.';$('#owner-view').hidden=!owner;$('#consumer-view').hidden=owner;$('#consumer-link').hidden=!owner;
if(owner){$('#consumer-link').href='/#access='+encodeURIComponent(state.consumerToken);$('#recovery').hidden=!state.pending;$('#sources').replaceChildren();for(const entry of state.entries){const card=node('article',null,'card');card.append(node('h3',entry),node('p','Source file · not automatically in your Wallet'),button('Preview '+entry,()=>showPreview(entry)));$('#sources').append(card);}
$('#items').replaceChildren();if(!state.items.length)$('#items').append(node('p','Your Wallet is empty. Preview a source email, then add it here.'));
for(const item of state.items){const card=node('article',null,'card'),details=node('details'),dl=node('dl');card.append(node('h3',item.title),node('span',item.sharing,'status'),node('p',item.classification==='private'?'Private · owner only':'Eligible readers: owner and demo consumer'));for(const [label,value] of [['Source',item.entry],['Source identity',item.sourceId],['Resource',item.resource.resourceId],['Version',item.resource.versionId],['SHA-256',item.resource.sha256],['Admitted',item.importedAt],['Mode','Immutable managed copy']])dl.append(node('dt',label),node('dd',value));details.append(node('summary','Inspect provenance and exact version'),dl);card.append(details,button('Open managed copy',()=>read(item.id)));
const granted=item.sharing.startsWith('Granted');card.append(button('Grant consumer access',()=>mutate('grant',{id:item.id}),granted||!!state.pending),button('Revoke access',()=>mutate('revoke',{id:item.id}),!granted||!!state.pending));$('#items').append(card);}
}else{$('#consumer-items').replaceChildren();if(!state.items.length)$('#consumer-items').append(node('p','No demo entries yet. Add a document in the owner view, then refresh here.'));for(const item of state.items){const card=node('article',null,'card');card.append(node('h3',item.title),node('p','Generic test entry; no document metadata is disclosed before the read succeeds.'),button('Try to open '+item.title,()=>read(item.id)));$('#consumer-items').append(card);}}
}
async function refresh(){clearResult();try{state=await api('/api/state');render();}catch(error){message(error.message,true);state=null;preview=null;$('#preview').hidden=true;$('#sources').replaceChildren();$('#items').replaceChildren();$('#consumer-items').replaceChildren();throw error;}}
async function task(action){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await action();}catch(error){message(error.message,true);}finally{busy=false;if(state)render();$('#refresh').disabled=false;$('#admit').disabled=!preview||!!state?.pending;$('#cancel').disabled=false;$('#retry').disabled=false;}}
async function showPreview(entry){await task(async()=>{preview=await api('/api/action',{action:'preview',payload:{entry}});$('#preview-title').textContent=entry;$('#preview-body').textContent=preview.text;$('#preview').hidden=false;$('#policy').value='restricted';message('Review the source bytes, then choose the copy’s permitted readers.');$('#preview').scrollIntoView({behavior:'smooth',block:'center'});});}
async function submit(action,payload){try{const receipt=await api('/api/action',{action,payload});await refresh();if(action==='admit'){$('#preview').hidden=true;preview=null;}message(action==='admit'?'Added to your Wallet. Consumer access is not granted yet.':action==='grant'?'Grant recorded. Try opening the document in the demo consumer view.':'Access revoked. A new consumer read will be denied.');return receipt;}catch(error){try{await refresh();}catch{}throw error;}}
async function mutate(action,payload){await task(()=>submit(action,{...payload,key:crypto.randomUUID()}));}
async function read(id){await task(async()=>{clearResult();$('#decision').textContent='Checking access…';$('#decision-detail').textContent='';$('#result').hidden=false;try{const result=await api('/api/action',{action:'read',payload:{id}});$('#decision').textContent='Access allowed';$('#decision-detail').textContent=(state.role==='owner'?'The owner':'The consumer')+' read these bytes through the Connector after Wallet authorisation.';$('#content').textContent=result.text;$('#content').hidden=false;$('#result').className='allowed';message('Live read succeeded.');}catch(error){$('#decision').textContent=error.code==='denied'?'Access denied':'Read unavailable';$('#decision-detail').textContent=error.message;$('#result').className='denied';message(error.message,true);}$('#result').scrollIntoView({behavior:'smooth',block:'center'});});}
$('#refresh').addEventListener('click',()=>task(async()=>{await refresh();message('Refreshed from the running services.');}));
$('#admit').addEventListener('click',()=>{if(preview)mutate('admit',{entry:preview.entry,sha256:preview.sha256,policy:$('#policy').value});});
$('#cancel').addEventListener('click',()=>{$('#preview').hidden=true;preview=null;});
$('#retry').addEventListener('click',()=>{if(state?.pending)task(()=>submit(state.pending.action,state.pending.payload));});
document.addEventListener('visibilitychange',()=>{if(document.hidden)clearResult();});
task(async()=>{await refresh();message(state.role==='owner'?'Start with a source preview on the left.':'Try a read before and after the owner grants access.');});
